package game.server.biomes;

import game.assets.StructureCollectionIdentifier;
import game.server.generation.GenerationData;

import static game.utils.Constants.*;
import static game.assets.StructureCollectionIdentifier.*;

public final class BiomesCache {

    public static final Biome
            CORRODED_MESA = new CorrodedMesa(),
            COLD_OCEAN = new ColdOcean(),
            MOUNTAIN = new Mountain(),
            DRY_MOUNTAIN = new DryMountain(),
            SNOWY_MOUNTAIN = new SnowyMountain(),
            BEACH = new HomogenousSurfaceBiome("Beach",
                    null, 0,
                    SHRUB, 64,
                    48, SAND),
            WASTELAND = new NoisySurfaceBiome("Wasteland",
                    BLACK_WOOD_TREES, 8,
                    SHRUB, 16,
                    48, GenerationData::getGeneratingDirtType),
            OCEAN = new NoisySurfaceBiome("Ocean",
                    null, 0,
                    null, 0,
                    48, GenerationData::getOceanFloorMaterial),
            WARM_OCEAN = new NoisySurfaceBiome("Warm Ocean",
                    null, 0,
                    null, 0,
                    48, GenerationData::getWarmOceanFloorMaterial),
            REDWOOD_FOREST = new NoisyLayeredSurfaceBiome("Redwood Forest",
                    REDWOOD_TREES, 128,
                    null, 0,
                    8, 48, DIRT, GenerationData::getGeneratingGrassType),
            PLAINS = new LayeredSurfaceBiome("Plains",
                    OAK_TREES, 32,
                    null, 0,
                    8, 48, GRASS, DIRT),
            SNOWY_PLAINS = new HomogenousSurfaceBiome("Snowy Plains",
                    SPRUCE_TREES, 32,
                    null, 0,
                    48, SNOW),
            BLACK_WOOD_FOREST = new LayeredSurfaceBiome("Black Wood Forest",
                    BLACK_WOOD_TREES, 128,
                    null, 0,
                    8, 48, PODZOL, DIRT),
            DARK_OAK_FOREST = new LayeredSurfaceBiome("Dark Oak Forest",
                    DARK_OAK_TREES, 128,
                    null, 0,
                    8, 48, PODZOL, DIRT),
            OAK_FOREST = new LayeredSurfaceBiome("Oak Forest",
                    OAK_TREES, 128,
                    null, 0,
                    8, 48, GRASS, DIRT),
            PINE_FOREST = new LayeredSurfaceBiome("Pine Forest",
                    PINE_TREES, 128,
                    null, 0,
                    8, 48, GRASS, DIRT),
            SNOWY_SPRUCE_FOREST = new HomogenousSurfaceBiome("Snowy Spruce Forest",
                    SPRUCE_TREES, 128,
                    null, 0,
                    48, SNOW),
            SPRUCE_FOREST = new LayeredSurfaceBiome("Spruce Forest",
                    SPRUCE_TREES, 128,
                    null, 0,
                    8, 48, GRASS, DIRT),
            MESA = new LayeredSurfaceBiome("Mesa",
                    null, 0,
                    StructureCollectionIdentifier.merge(new StructureCollectionIdentifier[]{CACTUS, SHRUB}, new float[]{0.5F, 0.5F}), 64,
                    48, 128, RED_SAND, RED_SANDSTONE),
            DESERT = new LayeredSurfaceBiome("Desert",
                    null, 0,
                    StructureCollectionIdentifier.merge(new StructureCollectionIdentifier[]{CACTUS, SHRUB}, new float[]{0.5F, 0.5F}), 64,
                    48, 128, SAND, SANDSTONE);
}
